### ISSUE TITLE
Live Preview. HTML. Not updated at change a attached files

### ISSUE THREAD

**Issue by IgorNovozhilov** [searKing/preview-vscode#6]
Preview is not updated when you change the stylesheets, and scripts attached to the html file using the tags `link` and `script`.

- VSCode Version:
![2017-01-23_09h27_36](https://cloud.githubusercontent.com/assets/3082812/22193698/3272e922-e14e-11e6-9f7f-d3dc7efea323.png)

- OS Version: Linux Mint 18 x64

- Preview version: 1.1.1

Steps to Reproduce:
Files from the example: [test-files.zip](https://github.com/Microsoft/vscode/files/613889/test-files.zip)

1. If I embed the styles and scripts directly in the html, when you change the code preview is updated.

![image](https://cloud.githubusercontent.com/assets/3082812/20635451/3bb93dfa-b36e-11e6-9249-5c69432d6924.png)

2. If I use the tags `link` and `script` code changes not covered in the preview.

sample html
![image](https://cloud.githubusercontent.com/assets/3082812/20635495/babb10ce-b36e-11e6-91dd-0482218ed8c2.png)

change code in file `test2.js`, the changes are not applied
![image](https://cloud.githubusercontent.com/assets/3082812/20635497/c0300334-b36e-11e6-8562-83f6bc9777a1.png)

**Comment by soulchainer** [comment]
And it's not only that: I think that the real problem is that it doesn't update if you don't edit it directly from the HTML tab, because you don't have the focus in that tab.
Like, in my case, rendering a pug template. Like the changes in the HTML are triggered from another tab, it doesn't update at all. You need to go to the HTML tab and do any other change to it to apply.

So, in the wide majority of **practical** usage related with HTML, the extension is not useful :(.

**Comment by AntonioRedondo** [comment]
Live preview doesn't work for `md` files at all for me. Every time I make a change to the file I'll have to open a new Preview tab.

**Comment by searKing** [comment]
Hi, Preview[2.3.2] is updated to use the Markdown API, Now Live Preview is supported.
